name: Publish qwc-qgis-server docker images

on: [push, workflow_dispatch]

jobs:

    build:
      runs-on: ubuntu-latest
      steps:

      - uses: actions/checkout@master

      - name: Get version tag QGIS 3 LTR
        id: get_tag_qgis_3_ltr
        run: |
          VERSION_TRIPLE=$(curl -s https://ubuntu.qgis.org/ubuntu-ltr/dists/jammy/main/binary-amd64/Packages | grep -A 2 "Package: qgis-server$" | grep Version | sed 's/^Version: 1:\(.*\)+.*/\1/')
          VERSION_MINOR=$(curl -s https://ubuntu.qgis.org/ubuntu-ltr/dists/jammy/main/binary-amd64/Packages | grep -A 2 "Package: qgis-server$" | grep Version | sed 's/^Version: 1:\([0-9]*\.[0-9]*\).*/\1/')
          echo ::set-output name=version::$VERSION_TRIPLE
          echo ::set-output name=minor::$VERSION_MINOR
          echo ::set-output name=tags::$VERSION_TRIPLE,$VERSION_MINOR

      - name: Build and publish docker image for QGIS Server 3 LTR
        uses: elgohr/Publish-Docker-Github-Action@v4
        env:
          QGIS_REPO: ubuntu-ltr
          URL_PREFIX: /ows
        with:
          name: sourcepole/qwc-qgis-server
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          tags: "${{ steps.get_tag_qgis_3_ltr.outputs.tags }}"
          workdir: .
          buildargs: QGIS_REPO,URL_PREFIX

      - name: Build and publish docker image for QGIS Server 3 LTR with plugins
        uses: elgohr/Publish-Docker-Github-Action@v4
        env:
          QGIS_VERSION: ${{ steps.get_tag_qgis_3_ltr.outputs.version }}
        with:
          name: sourcepole/qwc-qgis-server
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          tags: "${{ steps.get_tag_qgis_3_ltr.outputs.version }}-plugins,${{ steps.get_tag_qgis_3_ltr.outputs.minor }}-plugins"
          workdir: .
          dockerfile: Dockerfile-plugins
          buildargs: QGIS_VERSION

      - name: Build and publish docker image for QGIS Server 3 LTR with ODBC driver
        uses: elgohr/Publish-Docker-Github-Action@v4
        env:
          QGIS_VERSION: ${{ steps.get_tag_qgis_3_ltr.outputs.version }}
        with:
          name: sourcepole/qwc-qgis-server
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          tags: "${{ steps.get_tag_qgis_3_ltr.outputs.version }}-odbc,${{ steps.get_tag_qgis_3_ltr.outputs.minor }}-odbc"
          workdir: .
          dockerfile: Dockerfile-odbc
          buildargs: QGIS_VERSION

      - name: Get version tag QGIS 3
        id: get_tag_qgis_3
        run: |
          VERSION_TRIPLE=$(curl -s https://ubuntu.qgis.org/ubuntu/dists/jammy/main/binary-amd64/Packages | grep -A 2 "Package: qgis-server$" | grep Version | sed 's/^Version: 1:\(.*\)+.*/\1/')
          VERSION_MINOR=$(curl -s https://ubuntu.qgis.org/ubuntu/dists/jammy/main/binary-amd64/Packages | grep -A 2 "Package: qgis-server$" | grep Version | sed 's/^Version: 1:\([0-9]*\.[0-9]*\).*/\1/')
          echo ::set-output name=tags::$VERSION_TRIPLE,$VERSION_MINOR,latest

      - name: Build and publish docker image for QGIS Server 3
        uses: elgohr/Publish-Docker-Github-Action@v4
        env:
          URL_PREFIX: /ows
        with:
          name: sourcepole/qwc-qgis-server
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          tags: "${{ steps.get_tag_qgis_3.outputs.tags }}"
          workdir: .
          buildargs: URL_PREFIX
